# Q2. enter the eight number given by user and display the all unique number(onces)
s = set()
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
n=input("Enter the number: ")
s.add(int(n))
print(s)